### PR TITLE
Support multiple time labels in a single line and blank lines

### PR DESCRIPTION
**Pull request by BenzLeung**
## Support multiple time labels in a single line

```
[00:01.23][00:02.56]Do re mi
```

## Support blank lines

Lines with empty string, time labels only. For interludes of music.

```
[00:01.23]
```

### CODE REVIEW

**Comment by deluan** [comment]
Thanks, will merge this and update the dependency in Navidrome soon.

**Comment by BenzLeung** [comment]
I just made more fixes for lyrics.

## Fix time label conversion issue with more than 2-digit decimals

E.g. `[00:01:666]`.

Previously it would convert to **7660** ms. I fixed it to **1666** ms.

It needs to be merged with PR [#2368](https://github.com/navidrome/navidrome/pull/2368) to take effect.

## Minor bug fixes

See Files changed for `index.js`.

**Comment by deluan** [comment]
@apkatsikas I think https://github.com/navidrome/navidrome/pull/2656 also handles this, but I can be wrong. @kgarner7, can you confirm?

**Comment by kgarner7** [comment]
Yes, it handles that. In the frontend the structured lyrics are converted back to LRC format in `mm:ss.xx` format (https://github.com/navidrome/navidrome/blob/42c976b656d7e17795a79b3699165c3cf07029c2/ui/src/reducers/playerReducer.js#L51)

**Comment by deluan** [comment]
Thanks @BenzLeung, but we decided to fix this on the server. We are avoiding applying any changes to this fork of the player, as it is unmaintained now and we will be moving away from it.

This was superseded by https://github.com/navidrome/navidrome/pull/2656

**Pull request closed without merging**
